### ISSUE TITLE
Time stamps for chaos-1987-06-06

### ISSUE THREAD

**Issue by ams** [LM-3/chaos#71]
@larsbrinkhoff Time stamps on files, do we have anything?

https://github.com/LM-3/chaos/tree/chaos-1987-06-06

**Comment by larsbrinkhoff** [comment]
I should have the tarball lying around somewhere.

**Comment by larsbrinkhoff** [comment]
```
drwxr-xr-x 95969/nogroup     0 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/
-r--r--r-- 95969/nogroup  7601 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/if_chip.c
-r--r--r-- 95969/nogroup  5316 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chch11.c
-r--r--r-- 95969/nogroup  1819 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/ch11.h
-r--r--r-- 95969/nogroup   706 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chil.h
-r--r--r-- 95969/nogroup 13900 1990-07-17 17:28 bsd-4.3/vax/sys/attic/chncp/chncp.h
-r--r--r-- 95969/nogroup  2476 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/dr11c.h
-r--r--r-- 95969/nogroup  1110 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/address-res.h
-r--r--r-- 95969/nogroup  7785 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chdr11c.c
-r--r--r-- 95969/nogroup  7605 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chclock.c
-r--r--r-- 95969/nogroup 19525 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chrcv.c
-r--r--r-- 95969/nogroup 17854 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chil.c
-r--r--r-- 95969/nogroup  8450 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chsend.c
-r--r--r-- 95969/nogroup  8750 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chuser.c
-r--r--r-- 95969/nogroup  5827 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chstream.c
-r--r--r-- 95969/nogroup  5194 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chncp/chutil.c
lrwxr-xr-x 95969/nogroup     0 2011-08-24 20:20 bsd-4.3/vax/sys/attic/chncp/RCS -> ../../../../../../rcs/bsd-4.3/vax/sys/attic/chncp
drwxr-xr-x 95969/nogroup     0 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/
lrwxr-xr-x 95969/nogroup     0 2011-08-24 20:20 bsd-4.3/vax/sys/attic/chunix/RCS -> ../../../../../../rcs/bsd-4.3/vax/sys/attic/chunix
-r--r--r-- 95969/nogroup 13038 1987-05-25 17:58 bsd-4.3/vax/sys/attic/chunix/chtty.c
-r--r--r-- 95969/nogroup 24717 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/chaos.c
-r--r--r-- 95969/nogroup  1015 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/chtime.c
-r--r--r-- 95969/nogroup  9214 1987-06-09 01:45 bsd-4.3/vax/sys/attic/chunix/chether.c
-r--r--r-- 95969/nogroup   613 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/challoc.h
-r--r--r-- 95969/nogroup  3356 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/chsys.h
-r--r--r-- 95969/nogroup  1744 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/chconf.c
-r--r--r-- 95969/nogroup  2797 1990-07-17 17:28 bsd-4.3/vax/sys/attic/chunix/chconf.h
-r--r--r-- 95969/nogroup   482 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/chenet.h
-r--r--r-- 95969/nogroup  8693 1994-09-16 11:06 bsd-4.3/vax/sys/attic/chunix/challoc.c
-r--r--r-- 95969/nogroup  5361 1987-06-06 21:49 bsd-4.3/common/sys/h.vax_bsd43/chaos.h

**Comment by larsbrinkhoff** [comment]
Must be wrong tarball?!?

**Comment by ams** [comment]
No, that looks right.  If you look at the RCS ID for say chch11.c:

```
 * Revision 1.1  1994/09/16  11:06:20  cfields
 * Initial revision
 *
 * Revision 1.1  84/06/12  20:27:07  jis
 * Initial revision
```

Which means that someone got the sources, and plonked them into a new tree -- there by reseting the timestamps.

Can you upload, or send me the original tarball?

**Comment by larsbrinkhoff** [comment]
Note that one of the files is timestamped 1987.

**Comment by larsbrinkhoff** [comment]
[chaos.tar.gz](https://github.com/LM-3/chaos/files/3541089/chaos.tar.gz)

**Comment by ams** [comment]
Yeah, and some 1990 -- but those already existed in some RCS folder.

```
 *	$Source: /afs/dev.mit.edu/source/src77/bsd-4.3/vax/sys/attic/chncp/RCS/chil.c,v $
...
 * Revision 1.1  1994/09/16  11:06:27  cfields
```

```
 *	$Source: /source/bsd-4.3/vax/sys/chncp/chncp.h,v $
...
 * Revision 1.2  90/07/17  13:28:49  probe
```

I think that that this is a munge that occured when people copied a bunch of files from several different trees.

**Comment by ams** [comment]
I think this tree should rather be dated 1990-07-17, originally based on a tree from 1987 (1987-06-09).  The 1994 timestamps are a rouse.   When`cfields` in 1994 setup `/afs/dev.mit.edu/source/src77/bsd-4.3/vax/sys/attic/chncp` he started numbering from 1.1 (when he re-ci:ed the files).

The original location of this was once `/source/bsd-4.3/vax/sys`, where `probe` also did a re-ci of some files (1990-07-17), including some minor fixes for compiler issues.

As to why I claim that this is specifically based on something from 1987, is simply that `rc' did actual changes then (1987-06-12).  The initial copy of all the files is though from 1984.  Which is I guess when Symbolics forked the Chaosnet for Unix code, which is around there I think.

**Comment by ams** [comment]
Many of the RCS comments also match `chaos-1997-05-21` -- which is a somewhat garbaled tree with changes for Linux done by @lisper, that contains quite a bit of original timestamps -- about May 1987.

@lisper, You don't perchance still have a copy of the original netchaos code?  I.e. whatever was in /usr/src/sys/netchaos one some unknown machine.

**Comment by ams** [comment]
The 1984 code base seems to be from the Charon (VAX 11/750) gateway at MIT which was the gateway between Arpanet and Chaosnet (and during a brief period in 1984 was the only way to get to the Internet at Project Athena), it was functional up until 1990. Work was done by Jeffrey I. Schiller and Ramin Zabih when at the SIPB/MIT.

**Comment by ams** [comment]
On another note, the V8 tree that only contains chunix/chncp code, while dated

```
drwxrwxr-x 3/4               0 1985-05-29 06:14 usr/sys/chncp/
-rw-rw-r-- 3/4            5248 1985-03-27 14:49 usr/sys/chncp/chch11.c
-rw-rw-r-- 3/4            8022 1985-03-27 14:49 usr/sys/chncp/chclock.c
-rw-rw-r-- 3/4            7250 1985-03-27 14:49 usr/sys/chncp/chdr11c.c
-rw-rw-r-- 3/4           17606 1985-03-27 14:49 usr/sys/chncp/chil.c
-rw-rw-r-- 3/4           16448 1985-03-27 14:49 usr/sys/chncp/chrcv.c
-rw-rw-r-- 3/4            8770 1985-03-27 14:49 usr/sys/chncp/chsend.c
-rw-rw-r-- 3/4            5144 1985-03-27 14:49 usr/sys/chncp/chstream.c
-rw-rw-r-- 3/4            6974 1985-03-27 14:49 usr/sys/chncp/chuser.c
-rw-rw-r-- 3/4            4395 1985-03-27 14:49 usr/sys/chncp/chutil.c
-rw-rw-r-- 3/4             920 1985-03-27 14:49 usr/sys/chncp/testchil.c
drwxrwxr-x 3/4               0 1985-05-29 06:14 usr/sys/chunix/
-rw-rw-r-- 3/4            5300 1985-03-27 14:52 usr/sys/chunix/challoc.c
-rw-rw-rw- 3/4           19213 1985-03-27 14:52 usr/sys/chunix/chaos.c
-rw-rw-r-- 3/4             994 1985-03-27 14:52 usr/sys/chunix/chconf.c
-rw-rw-r-- 3/4            2050 1985-03-27 14:52 usr/sys/chunix/chconf.h
-rw-rw-r-- 3/4            2452 1985-03-27 14:52 usr/sys/chunix/chsys.h
-rw-rw-r-- 3/4             289 1985-03-27 14:52 usr/sys/chunix/chtime.c
-rw-rw-r-- 3/4            8756 1985-03-27 14:52 usr/sys/chunix/chtty.c
```

Is not from 1985 -- the code is from a period between 1982 and 1984.  E.g, `chstream.c` was modified such that it would accept an `errorp` argument between 1982 and 1984.  This change does not exist in the above V8 code. It also does not contain RCS headers.  Plus, the directory structure for the headers is the old split-style (e.g, `chaos.h` does not contain the literal content of `constants.h` but instead does an `#include`).

**Comment by larsbrinkhoff** [comment]
It's great you're seriously getting into historical software research!

Make tables, lots of them.

**Comment by ams** [comment]
I wasn't aware I ever stopped :-)  I'll try an contact the SIPB hackers and see if they have bits.

**Comment by ams** [comment]
Does anyone know when the Interlan Ethernet interface was introduced?

**Comment by larsbrinkhoff** [comment]
Maybe JNC.  He wrote this:

http://gunkies.org/wiki/Interlan_NI1010A/NI2010A_Ethernet_interface

**Comment by ams** [comment]
Thank you!  We also have Bitsavers to the rescue as always:

http://www.bitsavers.org/pdf/interlan/NI1010A_Unibus_Ethernet_Controller_Nov82.pdf
http://www.bitsavers.org/pdf/interlan/NI3010A_Multibus_Ethernet_Controller_Nov82.pdf

So this sets us in late 1982, which makes sense. and my diffs now look sensible in regard to the V8 code and the 1982 code.

**Comment by larsbrinkhoff** [comment]
Sounds great.  May your diffs always be sensible.

**Comment by ams** [comment]
To be exact, the tape from 1982-08-12 does not contain code for the Interlan Ethernet interface, the V8 code does.  It also kind means that`jis` introduced RCS headers to files if I am not wrong in 1984-06-12.  Alas, that means time stamps from those cannot be trusted since the timestamps might have been reset!

**Comment by ams** [comment]
My notes for posterity.

```
Notes on media and linage

chaos-19820812
	Original and complete tape; from DLW.

v8
	Contains kernel code (chncp/chunix), but no no user-space
	code.  While the tree is dated 1985, but the code under
	usr/sys/{chncp,chunix} is rather from between 1982 and 1984.

	E.g., chstream.c was modified such that it would accept an
	errorp argument between 1982 and 1984.  This change does not
	exist in the above V8 code.  It also does not contain RCS
	headers.  Plus, the directory structure for the headers is the
	old split-style (e.g, chaos.h does not contain the literal
	content of constants.h but instead does an #include).

chaos-19870606
	Incomplete dump of kernel code (chncp/chunix), no user-space
	code.

	I think this tree should rather be dated 1990-07-17,
	originally based on a tree from 1987 (1987-06-09).  The 1994
	timestamps are a rouse.  When cfields in 1994 setup
	/afs/dev.mit.edu/source/src77/bsd-4.3/vax/sys/attic/chncp he
	started numbering from 1.1 (when he re-ci:ed the files).

	The original location of this was once
	/source/bsd-4.3/vax/sys, where probe also did a re-ci of some
	files (1990-07-17), including some minor fixes for compiler
	issues.

	As to why I claim that this is specifically based on something
	from 1987, is simply that `rc' did actual changes then
	(1987-06-12).  The initial copy of all the files is though
	from 1984.  Which is I guess when Symbolics forked the
	Chaosnet for Unix code, which is around there I think.
	
chaos-19970521
	Contains many original files (~1989) as backup files, or
	unmodified.  Brad probobly started working on this in 1996?

chaos-19991124-0
	Contains RCS files but these are only one revision and not
	original.  Probobly a dump of the CVSROOT.
	
chaos-19991124-1
	Same as chaos-19991124 but a working copy.

chaos-20000703
	Continuation of above? Seems to be exactly same, but with RCS
	ids updates by me.

chaos-20010506
	Continuation of above.  Minor changes to keep up with Linux
	breakage.
```

**Comment by ams** [comment]
The Interlan interface is a EN-11.

**Comment by ams** [comment]
I've added all I know, and some linage details to https://github.com/LM-3/chaos/blob/master/NOTES .

**Comment by larsbrinkhoff** [comment]
Looks yummy!

**Comment by ams** [comment]
Closing, question has been answered.  Thank you @larsb!

**Comment by larsbrinkhoff** [comment]
> Closing, question has been answered. Thank you @larsb!

I think "larsb" will be surprised.
